language: elixir

matrix:
  include:
    - elixir: 1.0.5
      otp_release: 17.5
    - elixir: 1.1.1
      otp_release: 18.0
    - elixir: 1.2.2
      otp_release: 18.3
    - elixir: 1.3.4
      otp_release: 19.2
    - elixir: 1.4.5
      otp_release: 19.2
    - elixir: 1.5.3
      otp_release: 20.3
    - elixir: 1.6.4
      otp_release: 20.3
